---
hero_image: images/secret-messages.png
theme: red
duration: 2
listed: true
ingredient: false
copyedit: false
curriculum: 1, design-0, programming-1, phys-comp-0, manufacture-0, community-0
title: Tajne poruke
description: U ovom projektu naučit ćeš kako napraviti vlastiti program za šifriranje
  te poslati tajne poruke prijatelju i primiti tajne poruke prijatelja.
original_url: https://codeclubprojects.org/en-GB/python/secure-messages
interests: cybersecurity-and-cryptography
technologies: python
site_areas: projects
hardware: ''
software: python
version: 3
last_tested: 2017-01-01
steps:
- title: Uvod
- title: Cezarova šifra
- title: 'Izazov: Isprobaj Cezarovu šifru'
- title: Šifriranje slova
  completion:
  - engaged
- title: 'Izazov: Promjenjivi ključevi'
- title: Šifriranje poruka
- title: Dodatni znakovi
  completion:
  - internal
- title: 'Izazov: Šifriranje i dešifriranje poruka'