---
hero_image: images/secret-messages.png
theme: red
duration: 2
listed: true
ingredient: false
copyedit: false
curriculum: 1, design-0, programming-1, phys-comp-0, manufacture-0, community-0
title: Negeseuon Cyfrinachol
description: Gwnewch eich rhaglen amgryptio eich hun, i anfon a derbyn negeseuon cyfrinachol.
original_url: https://codeclubprojects.org/en-GB/python/secret-messages
interests: cybersecurity-and-cryptography
technologies: python
site_areas: projects
hardware: ''
software: python
version: 3
last_tested: 2017-01-01
steps:
  - title: Cyflwyniad
  - title: Seiffr Cesar
  - title: 'Her: Defnyddio seiffr Cesar'
  - title: Amgryptio llythyrau
  - title: 'Her: Allweddi amrywiol'
  - title: Amgryptio negeseuon cyfan
  - title: Cymeriadau ychwanegol
  - title: 'Her: Amgryptio a dadgryptio negeseuon'
  - title: 'Her: Cyfrifiannell cyfeillgarwch'
