---
hero_image: images/secret-messages.png
theme: red
duration: 2
listed: true
ingredient: false
copyedit: false
curriculum: 1, design-0, programming-1, phys-comp-0, manufacture-0, community-0
title: Geheime Nachrichten
description: Schreibe dein eigenes Verschlüsselungsprogramm, um geheime Nachrichten zu senden und zu empfangen.
original_url: https://codeclubprojects.org/en-GB/python/secret-messages
interests: cybersecurity-and-cryptography
technologies: python
site_areas: projects
hardware: ''
software: python
version: 3
last_tested: 2017-01-01
steps:
  - 
    title: 'Einleitung: '
  - 
    title: Die Caesar-Verschlüsselung
  - 
    title: 'Herausforderung: Benutze eine Caesar-Verschlüsselung'
  - 
    title: Buchstaben verschlüsseln
    completion:
      - engaged
  - 
    title: 'Herausforderung: Verschiedene Schlüssel'
  - 
    title: Komplette Nachrichten verschlüsseln
  - 
    title: Zusätzliche Zeichen
    completion:
      - internal
  - 
    title: 'Herausforderung: Verschlüsseln und Entschlüsseln von Nachrichten'
  - 
    title: 'Herausforderung: Freundschaftsrechner'
