---
hero_image: images / secret-messages.png
theme: vermelho
duration: 2
listed: true
ingredient: false
copyedit: false
curriculum: 1, design-0, programming-1, phys-comp-0, manufacture-0, community-0
title: Mensagens Secretas
description: Crie seu próprio programa de criptografia para enviar e receber mensagens secretas.
original_url: https://codeclubprojects.org/en-GB/python/secret-messages
interests: cybersecurity-and-cryptography
technologies: python
site_areas: projects
hardware: ''
software: python
version: 3
last_tested: 2017-01-01
steps:
  - 
    title: 'Introduction: '
  - 
    title: A cifra de César
  - 
    title: 'Desafio: use uma cifra de César'
  - 
    title: Criptografando cartas
  - 
    title: 'Desafio: teclas variáveis'
  - 
    title: Criptografando mensagens inteiras
  - 
    title: Caracteres extra
  - 
    title: 'Desafio: criptografar e descriptografar mensagens'
  - 
    title: 'Desafio: calculadora de amizade'
