---
hero_image: images/secret-messages.png
theme: red
duration: 2
listed: true
ingredient: false
copyedit: false
curriculum: 1, design-0, programming-1, phys-comp-0, manufacture-0, community-0
title: 秘密訊息
description: 製作自己的加密程序，用來發送和接收秘密的訊息。
original_url: https://codeclubprojects.org/zh-TW/python/secret-messages
interests: cybersecurity-and-cryptography
technologies: python
site_areas: projects
hardware: ''
software: python
version: 3
last_tested: 2017-01-01
steps:
- title: '介紹 '
- title: 凱撒密碼
- title: 挑戰：使用凱撒密碼
- title: 加密字母
  completion:
  - engaged
- title: 挑戰：可變的密鑰
- title: 加密整段訊息
- title: 多餘的字元
  completion:
  - internal
- title: 挑戰：加密和解密消息