---
hero_image: images/secret-messages.png
theme: red
duration: 2
listed: true
ingredient: false
copyedit: false
curriculum: 1, design-0, programming-1, phys-comp-0, manufacture-0, community-0
title: Messages secrets
description: Créer ton propre programme de chiffrement, pour envoyer et recevoir des
  messages secrets.
original_url: https://codeclubprojects.org/en-GB/python/secure-messages
interests: cybersecurity-and-cryptography
technologies: python
site_areas: projects
hardware: ''
software: python
version: 3
last_tested: 2017-01-01
steps:
- title: Introduction
- title: Le Code de César
- title: 'Défi: utiliser le Code de César'
- title: Crypter des lettres
  completion:
  - engaged
- title: 'Défi: clés variables'
- title: Crypter des messages entiers
- title: Caractères supplémentaires
  completion:
  - internal
- title: 'Défi: crypter et décrypter des messages'